apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: anomaly-predictor
  name: anomaly-predictor
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: '172.30.1.1:5000/test/anomaly-predictor'
