apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: anomaly-predictor
  name: miniconda3
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations:
        openshift.io/imported-from: continuumio/miniconda3
      from:
        kind: DockerImage
        name: continuumio/miniconda3
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
status:
  dockerImageRepository: '172.30.1.1:5000/test/miniconda3'
  tags:
    - items:
        - created: '2020-05-10T16:50:58Z'
          dockerImageReference: >-
            continuumio/miniconda3@sha256:456e3196bf3ffb13fee7c9216db4b18b5e6f4d37090b31df3e0309926e98cfe2
          generation: 2
          image: >-
            sha256:456e3196bf3ffb13fee7c9216db4b18b5e6f4d37090b31df3e0309926e98cfe2
      tag: latest