apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: anomaly-predictor
  name: anomaly-predictor
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'anomaly-predictor:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: 'https://github.com/Selllavi/anomaly-predictor.git'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'miniconda3:latest'
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: oahffyFtZRId-nQskHA8
      type: GitHub
    - generic:
        secret: kd0l_IzJvYUPJom2FtwO
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: >-
          continuumio/miniconda3@sha256:456e3196bf3ffb13fee7c9216db4b18b5e6f4d37090b31df3e0309926e98cfe2
      type: ImageChange